# Generated by Django 2.2.4 on 2020-07-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='icon',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
