# Generated by Django 2.2.4 on 2020-07-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_app', '0003_auto_20200724_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='icon_file',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
